title:            Marco Mengoli's Blog
description:      Blog that includes my notes on programming
disqus_shortname: mmblog
reading_time:     true
words_per_minute: 40
logo:             images/logo.png
url: https://marcomengoli.github.io
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
# url: http://aronbordin.com/neo-hpstr-jekyll-theme

menu:
  - title: 'Home'
    url: '/'
  - title: 'Tags'
    url: '/tags'
  - title: 'Categories'
    url: '/categories'
    type: 'categories'
  - title: 'About'
    url: '/about'
#  - title: 'Favorites'
#    url: '#'
#    submenu:
#      - title: 'highlighter'
#        url: '/code-highlighting-post/'
#      - title: 'intro'
#        url: '/readability-post/'

# Owner/author information
owner:
  name:           Marco Mengoli
  site:           https://www.marcomengoli.com/
  avatar:         images/avatar.jpg
  bio:            "Software Engineering student at University of Bologna. 
  I love to solve problems and experiment new things. 
  I'm an enthusiast maker, I love to make lots of projects with my Iot boards. I found on electronics a new really enjoyable hobby. 
  My favourite thematic is Software Engineering, in particular the continuous improvement of the quality of the products I develop and also the way I do it. 
  View more in the About page"
  email:          marco.mengoli4@yahoo.it
  # Social networking links used in footer. Update and remove as you like.
  # twitter: Marco Mengoli
  facebook: Marco Mengoli
  github: MarcoMengoli
  # stackexchange:
  linkedin:
  # instagram:
  # flickr:
  # tumblr:
  # google plus id, include the '+', eg +Marco Mengoli
  google_plus:    +Marco Mengoli

social:
  - title: "facebook"
    url: "https://www.facebook.com/MengoliMarco"
  - title: "linkedin"
    url: "https://it.linkedin.com/in/marco-mengoli-165abaa4"
  - title: "github"
    url: "https://github.com/MarcoMengoli"
  - title: "google-plus"
    url: "https://plus.google.com/112417882593672627749/posts"
# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Rome
future:      true


markdown:    kramdown


kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
  
gems:
  - jekyll-sitemap
  - jekyll-paginate
  
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 3


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
